"""add users and organizations for auth

Revision ID: 18c161f124ad
Revises: 35b1e328111d
Create Date: 2026-07-21 22:42:58.535172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c161f124ad'
down_revision = '35b1e328111d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###