"""add tasks and documents tables

Revision ID: 1bc122c085f7
Revises: 0d85042cace9
Create Date: 2026-07-23 15:27:38.316190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc122c085f7'
down_revision = '0d85042cace9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###