"""jira-style task fields

Revision ID: c91c743b9486
Revises: 59a816d34da1
Create Date: 2026-08-11 00:25:36.560688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91c743b9486'
down_revision = '59a816d34da1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_usage_log', sa.Column('organization_id', sa.UUID(), nullable=False, server_default='b36b4fa9-5f09-4cf2-90a1-a9bbc4969f23'))
    op.add_column('ai_usage_log', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('ai_usage_log', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('ai_usage_log', sa.Column('prompt_tokens', sa.String(length=50), nullable=True))
    op.add_column('ai_usage_log', sa.Column('completion_tokens', sa.String(length=50), nullable=True))
    op.add_column('ai_usage_log', sa.Column('status', sa.String(length=50), nullable=False, server_default='success'))
    op.alter_column('ai_usage_log', 'feature',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_foreign_key(None, 'ai_usage_log', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'ai_usage_log', 'users', ['user_id'], ['id'])
    op.drop_column('ai_usage_log', 'cost_estimate')
    op.drop_column('ai_usage_log', 'latency_ms')
    op.drop_column('ai_usage_log', 'tokens_used')
    op.alter_column('requirement_analyses', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_requirement_analyses_organization_id'), table_name='requirement_analyses')
    op.create_foreign_key(None, 'requirement_analyses', 'documents', ['document_id'], ['id'])
    op.create_foreign_key(None, 'requirement_analyses', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'requirement_analyses', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'requirement_analyses', 'projects', ['project_id'], ['id'])
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium'))
    op.add_column('tasks', sa.Column('story_points', sa.Numeric(precision=5, scale=1), nullable=True))
    op.add_column('tasks', sa.Column('labels', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'story_points')
    op.drop_column('tasks', 'priority')
    op.drop_constraint(None, 'requirement_analyses', type_='foreignkey')
    op.drop_constraint(None, 'requirement_analyses', type_='foreignkey')
    op.drop_constraint(None, 'requirement_analyses', type_='foreignkey')
    op.drop_constraint(None, 'requirement_analyses', type_='foreignkey')
    op.create_index(op.f('ix_requirement_analyses_organization_id'), 'requirement_analyses', ['organization_id'], unique=False)
    op.alter_column('requirement_analyses', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('ai_usage_log', sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_usage_log', sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('ai_usage_log', sa.Column('cost_estimate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_usage_log', type_='foreignkey')
    op.drop_constraint(None, 'ai_usage_log', type_='foreignkey')
    op.alter_column('ai_usage_log', 'feature',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('ai_usage_log', 'status')
    op.drop_column('ai_usage_log', 'completion_tokens')
    op.drop_column('ai_usage_log', 'prompt_tokens')
    op.drop_column('ai_usage_log', 'model')
    op.drop_column('ai_usage_log', 'user_id')
    op.drop_column('ai_usage_log', 'organization_id')
    # ### end Alembic commands ###