"""add clients table

Revision ID: 21145aada011
Revises: 18c161f124ad
Create Date: 2026-07-22 21:43:42.653790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21145aada011'
down_revision = '18c161f124ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###