"""add users and organizations for auth

Revision ID: 35b1e328111d
Revises: 18e1919dbbe9
Create Date: 2026-07-21 22:42:38.590205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b1e328111d'
down_revision = '18e1919dbbe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###